// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfgFe832f_8RCAfdIJe5UaYj_ODVc-yPU',
    appId: '1:363574853968:web:78653c404ba6e4d1feac55',
    messagingSenderId: '363574853968',
    projectId: 'mobileconatus',
    authDomain: 'mobileconatus.firebaseapp.com',
    storageBucket: 'mobileconatus.firebasestorage.app',
    measurementId: 'G-XKS1VVHKJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVzopJW-QEU3MxXBJ4OguCnHUG-yvZ-_Y',
    appId: '1:363574853968:android:2db6ac492e650a43feac55',
    messagingSenderId: '363574853968',
    projectId: 'mobileconatus',
    storageBucket: 'mobileconatus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0EHAsbz4fZVpPqt6tgcVMQX6lsB4fOIQ',
    appId: '1:363574853968:ios:fed53abfadb3efb6feac55',
    messagingSenderId: '363574853968',
    projectId: 'mobileconatus',
    storageBucket: 'mobileconatus.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0EHAsbz4fZVpPqt6tgcVMQX6lsB4fOIQ',
    appId: '1:363574853968:ios:fed53abfadb3efb6feac55',
    messagingSenderId: '363574853968',
    projectId: 'mobileconatus',
    storageBucket: 'mobileconatus.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfgFe832f_8RCAfdIJe5UaYj_ODVc-yPU',
    appId: '1:363574853968:web:9b1fc16b0b64b139feac55',
    messagingSenderId: '363574853968',
    projectId: 'mobileconatus',
    authDomain: 'mobileconatus.firebaseapp.com',
    storageBucket: 'mobileconatus.firebasestorage.app',
    measurementId: 'G-YCQB3TKPQY',
  );
}
