// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGx66p7sxQPcSnaPRjkt_w6z3Lcu1u4n4',
    appId: '1:455233680424:web:ae27edfa4fe3b961aa711d',
    messagingSenderId: '455233680424',
    projectId: 'uapmobile-67cfc',
    authDomain: 'uapmobile-67cfc.firebaseapp.com',
    storageBucket: 'uapmobile-67cfc.firebasestorage.app',
    measurementId: 'G-XN5QWM91LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNso7RP0h8jR-E3v5s6PzW3RSTGbMfcmM',
    appId: '1:455233680424:android:71f1d1f66a9d46b0aa711d',
    messagingSenderId: '455233680424',
    projectId: 'uapmobile-67cfc',
    storageBucket: 'uapmobile-67cfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5UsJmP3j6TCMHm5_mMzrFSeE-zYlOueM',
    appId: '1:455233680424:ios:18348b21ca910a16aa711d',
    messagingSenderId: '455233680424',
    projectId: 'uapmobile-67cfc',
    storageBucket: 'uapmobile-67cfc.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5UsJmP3j6TCMHm5_mMzrFSeE-zYlOueM',
    appId: '1:455233680424:ios:18348b21ca910a16aa711d',
    messagingSenderId: '455233680424',
    projectId: 'uapmobile-67cfc',
    storageBucket: 'uapmobile-67cfc.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGx66p7sxQPcSnaPRjkt_w6z3Lcu1u4n4',
    appId: '1:455233680424:web:10dd7694c82df71caa711d',
    messagingSenderId: '455233680424',
    projectId: 'uapmobile-67cfc',
    authDomain: 'uapmobile-67cfc.firebaseapp.com',
    storageBucket: 'uapmobile-67cfc.firebasestorage.app',
    measurementId: 'G-YSCDC5NH94',
  );

}